
services:
  docling-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: docling-api:latest
    container_name: docling-api
    restart: unless-stopped
   
    ports:
      - "7080:8000"
    
    volumes:
      # Persistent model cache to avoid re-downloading
      - docling-models:/app/models
      # Optional: if you want to access uploaded files from host
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    
    environment:
      - LOG_LEVEL=INFO
      # Optional: Set API key for authentication
      # - API_KEY=your-secret-key-here
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  docling-models:
    driver: local

networks:
  default:
    name: docling-network
